<?php

namespace Tests\Feature;

use App\Enums\EngineType;
use App\Services\UnrealAssetService;
use App\Support\GameEngineTemplates;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class Phase5Test extends TestCase
{
    use RefreshDatabase;

    // ── EngineType Enum ─────────────────────────────────────────────────────

    public function test_engine_type_enum_has_expected_cases(): void
    {
        $this->assertSame('unreal', EngineType::Unreal->value);
        $this->assertSame('unity', EngineType::Unity->value);
        $this->assertSame('godot', EngineType::Godot->value);
    }

    public function test_engine_type_labels(): void
    {
        $this->assertSame('Unreal Engine', EngineType::Unreal->label());
        $this->assertSame('Unity', EngineType::Unity->label());
        $this->assertSame('Godot', EngineType::Godot->label());
    }

    public function test_engine_type_icons(): void
    {
        $this->assertSame('UE', EngineType::Unreal->icon());
        $this->assertSame('U3D', EngineType::Unity->icon());
        $this->assertSame('GD', EngineType::Godot->icon());
    }

    public function test_engine_type_markers(): void
    {
        $this->assertContains('*.uproject', EngineType::Unreal->markers());
        $this->assertContains('project.godot', EngineType::Godot->markers());
        $this->assertContains('Assets/', EngineType::Unity->markers());
    }

    public function test_engine_type_template_names(): void
    {
        $this->assertSame('unreal', EngineType::Unreal->templateName());
        $this->assertSame('unity', EngineType::Unity->templateName());
        $this->assertSame('godot', EngineType::Godot->templateName());
    }

    // ── GameEngineTemplates ─────────────────────────────────────────────────

    public function test_templates_available_returns_all_templates(): void
    {
        $available = GameEngineTemplates::available();

        $this->assertContains('unreal', $available);
        $this->assertContains('unity', $available);
        $this->assertContains('godot', $available);
        $this->assertContains('general', $available);
    }

    public function test_unreal_template_includes_uasset(): void
    {
        $entries = GameEngineTemplates::unreal();
        $patterns = array_column($entries, 'pattern');

        $this->assertContains('*.uasset', $patterns);
        $this->assertContains('*.umap', $patterns);
        $this->assertContains('*.fbx', $patterns);
    }

    public function test_unity_template_includes_unity_scene(): void
    {
        $entries = GameEngineTemplates::unity();
        $patterns = array_column($entries, 'pattern');

        $this->assertContains('*.unity', $patterns);
        $this->assertContains('*.prefab', $patterns);
    }

    public function test_godot_template_includes_tscn(): void
    {
        $entries = GameEngineTemplates::godot();
        $patterns = array_column($entries, 'pattern');

        $this->assertContains('*.tscn', $patterns);
        $this->assertContains('*.tres', $patterns);
    }

    public function test_get_returns_null_for_unknown_template(): void
    {
        $this->assertNull(GameEngineTemplates::get('cryengine'));
    }

    public function test_to_gitattributes_generates_valid_content(): void
    {
        $entries = [
            ['pattern' => '*.uasset', 'description' => 'Unreal asset', 'lockable' => true],
            ['pattern' => '*.png', 'description' => 'PNG image', 'lockable' => false],
        ];

        $content = GameEngineTemplates::toGitattributes($entries);

        $this->assertStringContainsString('*.uasset filter=lfs diff=lfs merge=lfs -text', $content);
        $this->assertStringContainsString('*.png filter=lfs diff=lfs merge=lfs -text', $content);
        $this->assertStringContainsString('# Generated by Crucible SCM', $content);
    }

    public function test_unreal_template_marks_uasset_as_lockable(): void
    {
        $entries = GameEngineTemplates::unreal();
        $uasset = collect($entries)->firstWhere('pattern', '*.uasset');

        $this->assertNotNull($uasset);
        $this->assertTrue($uasset['lockable']);
    }

    // ── UnrealAssetService ──────────────────────────────────────────────────

    public function test_parse_returns_null_for_short_content(): void
    {
        $service = new UnrealAssetService;

        $this->assertNull($service->parse('short'));
    }

    public function test_parse_returns_null_for_invalid_magic(): void
    {
        $service = new UnrealAssetService;
        $contents = str_repeat("\x00", 100);

        $this->assertNull($service->parse($contents));
    }

    public function test_parse_valid_uasset_header(): void
    {
        $service = new UnrealAssetService;

        // Build a minimal valid .uasset header
        $contents = pack('V', 0x9E2A83C1);   // Magic
        $contents .= pack('l', -7);            // Legacy file version
        $contents .= pack('l', 0);             // Legacy UE3 version
        $contents .= pack('l', 522);           // File version UE4 (4.27)
        $contents .= pack('l', 0);             // File version licensee
        $contents .= str_repeat("\x00", 200);  // Padding

        $meta = $service->parse($contents);

        $this->assertNotNull($meta);
        $this->assertTrue($meta['valid']);
        $this->assertSame('0x9E2A83C1', $meta['magic']);
        $this->assertSame(522, $meta['file_version_ue4']);
        $this->assertSame('UE 4.27', $meta['engine_version']);
    }

    public function test_parse_ue5_version_detection(): void
    {
        $service = new UnrealAssetService;

        $contents = pack('V', 0x9E2A83C1);
        $contents .= pack('l', -7);
        $contents .= pack('l', 0);
        $contents .= pack('l', 1004);  // UE 5.2
        $contents .= pack('l', 0);
        $contents .= str_repeat("\x00", 200);

        $meta = $service->parse($contents);

        $this->assertNotNull($meta);
        $this->assertSame('UE 5.2', $meta['engine_version']);
    }

    public function test_classify_asset_detects_blueprint(): void
    {
        $service = new UnrealAssetService;

        // Build content that contains "BlueprintGeneratedClass"
        $contents = pack('V', 0x9E2A83C1);
        $contents .= str_repeat("\x00", 100);
        $contents .= 'BlueprintGeneratedClass';
        $contents .= str_repeat("\x00", 100);

        $this->assertSame('Blueprint', $service->classifyAsset($contents));
    }

    public function test_classify_asset_detects_static_mesh(): void
    {
        $service = new UnrealAssetService;

        $contents = pack('V', 0x9E2A83C1);
        $contents .= str_repeat("\x00", 100);
        $contents .= 'StaticMesh';
        $contents .= str_repeat("\x00", 100);

        $this->assertSame('Static Mesh', $service->classifyAsset($contents));
    }

    public function test_classify_asset_detects_texture(): void
    {
        $service = new UnrealAssetService;

        $contents = pack('V', 0x9E2A83C1);
        $contents .= str_repeat("\x00", 100);
        $contents .= 'Texture2D';
        $contents .= str_repeat("\x00", 100);

        $this->assertSame('Texture', $service->classifyAsset($contents));
    }

    public function test_classify_asset_returns_unknown_for_unrecognized(): void
    {
        $service = new UnrealAssetService;

        $contents = str_repeat("\x00", 300);

        $this->assertSame('Unknown Asset', $service->classifyAsset($contents));
    }

    public function test_extract_dependencies_finds_game_paths(): void
    {
        $service = new UnrealAssetService;

        $contents = "some binary data /Game/Textures/T_Hero more data /Engine/Materials/DefaultMaterial end";

        $deps = $service->extractDependencies($contents);

        $this->assertContains('/Game/Textures/T_Hero', $deps);
        $this->assertContains('/Engine/Materials/DefaultMaterial', $deps);
    }

    public function test_extract_dependencies_returns_empty_for_no_paths(): void
    {
        $service = new UnrealAssetService;

        $deps = $service->extractDependencies('no paths here');

        $this->assertEmpty($deps);
    }

    public function test_summary_returns_error_for_invalid_asset(): void
    {
        $service = new UnrealAssetService;

        $result = $service->summary('invalid');

        $this->assertArrayHasKey('error', $result);
    }

    public function test_summary_returns_complete_data_for_valid_asset(): void
    {
        $service = new UnrealAssetService;

        // Build a minimal valid .uasset with a known class
        $contents = pack('V', 0x9E2A83C1);   // Magic
        $contents .= pack('l', -7);            // Legacy file version
        $contents .= pack('l', 0);             // Legacy UE3 version
        $contents .= pack('l', 1000);          // File version UE4 (5.0)
        $contents .= pack('l', 0);             // File version licensee
        $contents .= str_repeat("\x00", 100);
        $contents .= 'StaticMesh';
        $contents .= str_repeat("\x00", 50);
        $contents .= '/Game/Meshes/SM_Wall';
        $contents .= str_repeat("\x00", 50);

        $summary = $service->summary($contents);

        $this->assertSame('Static Mesh', $summary['asset_class']);
        $this->assertSame('UE 5.0', $summary['engine_version']);
        $this->assertSame(1000, $summary['file_version']);
        $this->assertIsArray($summary['dependencies']);
        $this->assertContains('/Game/Meshes/SM_Wall', $summary['dependencies']);
    }

    // ── Repository Engine Type ──────────────────────────────────────────────

    public function test_repository_model_casts_engine_type(): void
    {
        // Test using in-memory model (no factory needed)
        $repo = new \App\Models\Repository([
            'engine_type' => 'unreal',
        ]);

        $this->assertInstanceOf(EngineType::class, $repo->engine_type);
        $this->assertSame(EngineType::Unreal, $repo->engine_type);
    }

    public function test_repository_engine_type_nullable(): void
    {
        $repo = new \App\Models\Repository([
            'engine_type' => null,
        ]);

        $this->assertNull($repo->engine_type);
    }

    public function test_repository_engine_type_all_values(): void
    {
        foreach (EngineType::cases() as $type) {
            $repo = new \App\Models\Repository([
                'engine_type' => $type->value,
            ]);
            $this->assertSame($type, $repo->engine_type);
        }
    }

    // ── Engine Version Guessing ─────────────────────────────────────────────

    public function test_guess_engine_version_covers_all_ranges(): void
    {
        $service = new UnrealAssetService;

        // Test via parse (which calls guessEngineVersion internally)
        $versions = [
            0    => 'Unknown',
            503  => 'UE 4.18',
            504  => 'UE 4.19',
            505  => 'UE 4.20',
            508  => 'UE 4.21',
            510  => 'UE 4.22',
            513  => 'UE 4.23',
            514  => 'UE 4.24',
            516  => 'UE 4.25',
            518  => 'UE 4.26',
            522  => 'UE 4.27',
            1000 => 'UE 5.0',
            1002 => 'UE 5.1',
            1004 => 'UE 5.2',
            1007 => 'UE 5.3',
            1008 => 'UE 5.4',
            1009 => 'UE 5.5+',
            1050 => 'UE 5.5+',
        ];

        foreach ($versions as $fileVersion => $expected) {
            $contents = pack('V', 0x9E2A83C1);
            $contents .= pack('l', -7);
            $contents .= pack('l', 0);
            $contents .= pack('l', $fileVersion);
            $contents .= pack('l', 0);
            $contents .= str_repeat("\x00", 200);

            $meta = $service->parse($contents);
            $this->assertNotNull($meta, "parse() returned null for file version {$fileVersion}");
            $this->assertSame($expected, $meta['engine_version'], "Version mismatch for file version {$fileVersion}");
        }
    }
}
